/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Abel Gomez
 */
public class vistaMedicamentos extends javax.swing.JFrame {

    /**
     * Creates new form vistaMedicamentos
     */
    public vistaMedicamentos() {
        initComponents();
    }

    public JDialog getjDialogMedicamento() {
        return jDialogMedicamento;
    }

    public void setjDialogMedicamento(JDialog jDialogMedicamento) {
        this.jDialogMedicamento = jDialogMedicamento;
    }

    public JTable getTablaMedicamemntos() {
        return tablaMedicamemntos;
    }

    public void setTablaMedicamemntos(JTable tablaMedicamemntos) {
        this.tablaMedicamemntos = tablaMedicamemntos;
    }

    public JButton getBtnatras() {
        return btnatras;
    }

    public void setBtnatras(JButton btnatras) {
        this.btnatras = btnatras;
    }
    
    
    

    public JButton getBtnGuardarMedicamento() {
        return btnGuardarMedicamento;
    }

    public void setBtnGuardarMedicamento(JButton btnGuardarMedicamento) {
        this.btnGuardarMedicamento = btnGuardarMedicamento;
    }

    public JButton getBtnNuevoPedido() {
        return btnNuevoPedido;
    }

    public void setBtnNuevoPedido(JButton btnNuevoPedido) {
        this.btnNuevoPedido = btnNuevoPedido;
    }

    public ButtonGroup getDistribuidorgrupo() {
        return distribuidorgrupo;
    }

    public void setDistribuidorgrupo(ButtonGroup distribuidorgrupo) {
        this.distribuidorgrupo = distribuidorgrupo;
    }

    public JCheckBox getjCheckBoxPrincipal1() {
        return jCheckBoxPrincipal1;
    }

    public void setjCheckBoxPrincipal1(JCheckBox jCheckBoxPrincipal1) {
        this.jCheckBoxPrincipal1 = jCheckBoxPrincipal1;
    }

    public JCheckBox getjCheckBoxSECUNDARIA1() {
        return jCheckBoxSECUNDARIA1;
    }

    public void setjCheckBoxSECUNDARIA1(JCheckBox jCheckBoxSECUNDARIA1) {
        this.jCheckBoxSECUNDARIA1 = jCheckBoxSECUNDARIA1;
    }
    
    
    

    public JRadioButton getjRadioButtonCEMEFAR1() {
        return jRadioButtonCEMEFAR1;
    }

    public void setjRadioButtonCEMEFAR1(JRadioButton jRadioButtonCEMEFAR1) {
        this.jRadioButtonCEMEFAR1 = jRadioButtonCEMEFAR1;
    }

    public JRadioButton getjRadioButtonCOFARMA1() {
        return jRadioButtonCOFARMA1;
    }

    public void setjRadioButtonCOFARMA1(JRadioButton jRadioButtonCOFARMA1) {
        this.jRadioButtonCOFARMA1 = jRadioButtonCOFARMA1;
    }

    public JRadioButton getjRadioButtonEMPSEPHAR1() {
        return jRadioButtonEMPSEPHAR1;
    }

    public void setjRadioButtonEMPSEPHAR1(JRadioButton jRadioButtonEMPSEPHAR1) {
        this.jRadioButtonEMPSEPHAR1 = jRadioButtonEMPSEPHAR1;
    }

    public JSpinner getjSpinnerCantidad1() {
        return jSpinnerCantidad1;
    }

    public void setjSpinnerCantidad1(JSpinner jSpinnerCantidad1) {
        this.jSpinnerCantidad1 = jSpinnerCantidad1;
    }

    public JComboBox<String> getJcmbBxTipo1() {
        return jcmbBxTipo1;
    }

    public void setJcmbBxTipo1(JComboBox<String> jcmbBxTipo1) {
        this.jcmbBxTipo1 = jcmbBxTipo1;
    }

    public JTextField getTxtNombre1() {
        return txtNombre1;
    }

    public void setTxtNombre1(JTextField txtNombre1) {
        this.txtNombre1 = txtNombre1;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        distribuidorgrupo = new javax.swing.ButtonGroup();
        jDialogMedicamento = new javax.swing.JDialog();
        jcmbBxTipo1 = new javax.swing.JComboBox<>();
        jSpinnerCantidad1 = new javax.swing.JSpinner();
        jRadioButtonCOFARMA1 = new javax.swing.JRadioButton();
        jRadioButtonEMPSEPHAR1 = new javax.swing.JRadioButton();
        jRadioButtonCEMEFAR1 = new javax.swing.JRadioButton();
        jCheckBoxPrincipal1 = new javax.swing.JCheckBox();
        jCheckBoxSECUNDARIA1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        btnGuardarMedicamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicamemntos = new javax.swing.JTable();
        btnNuevoPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jcmbBxTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ...", "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo ", "antibióticos" }));
        jcmbBxTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbBxTipo1ActionPerformed(evt);
            }
        });

        jSpinnerCantidad1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        distribuidorgrupo.add(jRadioButtonCOFARMA1);
        jRadioButtonCOFARMA1.setText("COFARMA");
        jRadioButtonCOFARMA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCOFARMA1ActionPerformed(evt);
            }
        });

        distribuidorgrupo.add(jRadioButtonEMPSEPHAR1);
        jRadioButtonEMPSEPHAR1.setText("EMPSEPHAR ");
        jRadioButtonEMPSEPHAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEMPSEPHAR1ActionPerformed(evt);
            }
        });

        distribuidorgrupo.add(jRadioButtonCEMEFAR1);
        jRadioButtonCEMEFAR1.setText("CEMEFAR");

        jCheckBoxPrincipal1.setText("PRINCIPAL");
        jCheckBoxPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPrincipal1ActionPerformed(evt);
            }
        });

        jCheckBoxSECUNDARIA1.setText("SECUNDARIA");
        jCheckBoxSECUNDARIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSECUNDARIA1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre: ");

        jLabel7.setText("Tipo :");

        jLabel8.setText("Cantidad :");

        jLabel9.setText("Sucursal:");

        jLabel10.setText("Distribuidor :");

        btnGuardarMedicamento.setText("Guardar");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Pedido ");

        btnatras.setText("Atras");

        javax.swing.GroupLayout jDialogMedicamentoLayout = new javax.swing.GroupLayout(jDialogMedicamento.getContentPane());
        jDialogMedicamento.getContentPane().setLayout(jDialogMedicamentoLayout);
        jDialogMedicamentoLayout.setHorizontalGroup(
            jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                                .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(jRadioButtonEMPSEPHAR1)
                                        .addComponent(jRadioButtonCEMEFAR1)
                                        .addComponent(jRadioButtonCOFARMA1)))
                                .addGap(46, 46, 46)
                                .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jcmbBxTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBoxSECUNDARIA1)
                                    .addComponent(jCheckBoxPrincipal1)
                                    .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSpinnerCantidad1)
                        .addGap(257, 257, 257)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jDialogMedicamentoLayout.setVerticalGroup(
            jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbBxTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxPrincipal1)
                        .addGap(37, 37, 37)
                        .addComponent(jCheckBoxSECUNDARIA1))
                    .addGroup(jDialogMedicamentoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCOFARMA1)
                        .addGap(11, 11, 11)
                        .addComponent(jRadioButtonEMPSEPHAR1)
                        .addGap(8, 8, 8)
                        .addComponent(jRadioButtonCEMEFAR1)))
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jSpinnerCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jDialogMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMedicamento)
                    .addComponent(btnatras))
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMedicamemntos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo", "Cantidad", "Distribuidor ", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMedicamemntos);

        btnNuevoPedido.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnNuevoPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-plus-48.png"))); // NOI18N
        btnNuevoPedido.setText("Nuevo pedido");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-caduceus-50.png"))); // NOI18N
        jLabel2.setText("Tienda de Medicamentos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1048, 1048, 1048)
                .addComponent(btnNuevoPedido)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel2)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoPedido)
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxSECUNDARIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSECUNDARIA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxSECUNDARIA1ActionPerformed

    private void jCheckBoxPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPrincipal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxPrincipal1ActionPerformed

    private void jRadioButtonEMPSEPHAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEMPSEPHAR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEMPSEPHAR1ActionPerformed

    private void jRadioButtonCOFARMA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCOFARMA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCOFARMA1ActionPerformed

    private void jcmbBxTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbBxTipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbBxTipo1ActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistaMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistaMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistaMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistaMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vistaMedicamentos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMedicamento;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnatras;
    private javax.swing.ButtonGroup distribuidorgrupo;
    private javax.swing.JCheckBox jCheckBoxPrincipal1;
    private javax.swing.JCheckBox jCheckBoxSECUNDARIA1;
    private javax.swing.JDialog jDialogMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCEMEFAR1;
    private javax.swing.JRadioButton jRadioButtonCOFARMA1;
    private javax.swing.JRadioButton jRadioButtonEMPSEPHAR1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad1;
    private javax.swing.JComboBox<String> jcmbBxTipo1;
    private javax.swing.JTable tablaMedicamemntos;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
